### ISSUE TITLE
Module 'dns' has no attribute 'message'.

### ISSUE THREAD

**Issue by Fizwizbiz** [lanmaster53/recon-ng-marketplace#107]
Hello everyone ! 

I'm new with recon-ng, and for the first try I tried to use the module cache-snoop, I put a correct and functional IP in NAMESERVER and run it, but i've got this message, "Module 'dns' has no attribute 'message'.". I tried with others IP and I still get this message, don't know what the issue here. If someone could help me :) 

Thanks !

**Comment by MrJester** [comment]
Confirmed issue will work on this at some point soon.

**Comment by 0x646e78** [comment]
I haven't experienced this at all. 

Python 3.7 & 3.8, recon-ng 5.1.1, cache_snoop 1.0, Alpine Linux and Fedora 21-23.

**Comment by lanmaster53** [comment]
Is this still an issue?

**Comment by MrJester** [comment]
This appears to not be an issue I'm Running Kali Rolling Python 3.8.3

**Comment by lanmaster53** [comment]
Thanks @MrJester !
