### ISSUE TITLE
Scylla is asking for authentication

### ISSUE THREAD

**Issue by aayush420** [lanmaster53/recon-ng-marketplace#113]
**Module Name**
Which module is affected?
https://github.com/lanmaster53/recon-ng-marketplace/tree/master/modules/recon/domains-credentials/scylla.py

**Bug Description**
The module is failing when run, as Scylla is asking for authentication for querying. There is no registration part and no API key to set. It just fails. 

**Steps to Reproduce**
1. Add a domain.
2. Load module recon/domains-credentials/scylla
3. Run it.
4. See error. Make the global verbosity to 2 for viewing the actual debug info of the error. 

**Expected Behavior**
Leaked credentials are to be collected from Scylla

**Additional Context**
Opening scylla.sh in browser directly is asking for authentication. All the links that were valid before, are asking for credentials.

**Comment by MrJester** [comment]
The owner placed the domain behind an auth wall. Will have to reach out and module needs to be updated.

**Comment by lanmaster53** [comment]
Reached out to him personally. Will let you know when I hear back.

**Comment by MrJester** [comment]
PR 124 is fixing this issue

**Comment by lanmaster53** [comment]
Resolved by #124
