### ISSUE TITLE
Incorrect title

### ISSUE THREAD

**Issue by leebaird** [lanmaster53/recon-ng-marketplace#120]
**Module Name**
Which module is affected?
https://github.com/lanmaster53/recon-ng-marketplace/tree/master/modules/recon/domains-contacts/hunter_io.py

**Bug Description**
Module adds incorrect title of "Hunter.io Contact"

**Solution**
Delete line 85.

**Comment by MrJester** [comment]
Confirmed go ahead and submit a PR please.
