### ISSUE TITLE
Unable to geocode

### ISSUE THREAD

**Issue by GooBalll** [lanmaster53/recon-ng-marketplace#134]
CEH Lab 14

When trying to geocode a location, the result is "Unable to geocode"
Attempts with latitude, longitude, street address or all three, the result is still "Unable to geocode"

I also did a marketplace refresh, and updated recon-ng.

**Comment by lanmaster53** [comment]
Transferred to the proper repo.

I have no idea how CEH is using Recon-ng, but there are a couple things that could cause this. First, make sure you have a valid Google API key added to the framework and that the proper APIs are enabled for that key. Second, perhaps Google simply can't geocode that location.

It does mean that the request and response is happening, there are just zero results in the response.

This isn't a bug, so I'm going to close the issue, but feel free to ask here or hit up the Slack if you need further assistance. Slack is probably your best bet for a relatively quick response. https://github.com/lanmaster53/recon-ng/wiki/Getting-Started#help
