### ISSUE TITLE
Error running scylla

### ISSUE THREAD

**Issue by malbaqari** [lanmaster53/recon-ng-marketplace#135]
Hi,

I am trying to run scylla but getting below error

[recon-ng][sd_external][scylla] > run
[!] Expecting value: line 1 column 1 (char 0).
[!] Something broken? See https://github.com/lanmaster53/recon-ng/wiki/Troubleshooting#issue-reporting.

**Comment by lanmaster53** [comment]
Transferred to proper repo.

This should have been fixed by 0af87d2badbfc104213c8906f7261efcc1baadc5 or 22296d9e2e4469f6bf237106e9e89d2405368315. I'm not sure which Scylla module you were using, but they were both patched and rested recently.
