### ISSUE TITLE
error with shodan module

### ISSUE THREAD

**Issue by realsumyunggai** [lanmaster53/recon-ng-marketplace#139]
**Module Name**
recon/domains-hosts/shodan_hostname

**Bug Description**
[!] Expecting value: line 1 column 1 (char 0).

**Steps to Reproduce**
1) start recon-ng
2) load module recon/domains-hosts/shodan_hostname
3) make sure source option is set
4) run module

**Expected Behavior**
Hosts should be found

**Screenshots**
\[If applicable, screenshots to help explain the problem.\]
![image](https://user-images.githubusercontent.com/66628275/84037376-8324a380-a96c-11ea-8c92-7c39e10f417b.png)

**Additional Context**
\[Any other context about the problem.\]

**Comment by lanmaster53** [comment]
Unable to replicate. Please set the verbosity to the debug setting and send the full output of the error. My guess is your system is having problems connecting to Shodan, causing the response from Shodan to be unexpected and break the parser.

```
[recon-ng][default][shodan_hostname] > options set SOURCE github.com
SOURCE => github.com
[recon-ng][default][shodan_hostname] > run

----------
GITHUB.COM
----------
[*] Searching Shodan API for: hostname:github.com
[*] Banner: None
[*] Host: lb-140-82-112-4-iad.github.com
[*] Ip_Address: 140.82.112.4
[*] Notes: None
[*] Port: 80
[*] Protocol: None
[*] --------------------------------------------------
...
[*] --------------------------------------------------
[*] Country: None
[*] Host: out-28.smtp.github.com
[*] Ip_Address: 192.30.252.211
[*] Latitude: None
[*] Longitude: None
[*] Notes: None
[*] Region: None
[*] --------------------------------------------------

-------
SUMMARY
-------
[*] 100 total (100 new) ports found.
[*] 100 total (69 new) hosts found.
[recon-ng][default][shodan_hostname] > 
```

**Comment by hksharmaa26** [comment]
@realsumyunggai you should add api key for shodan...correct one

**Comment by MrJester** [comment]
Also unable to replicate. Suggest using Slack if you need further help with this.
