### ISSUE TITLE
recon-ng hibp breach module

### ISSUE THREAD

**Issue by bu3skoor56** [lanmaster53/recon-ng-marketplace#149]
Dear team,

Why when i am searching about leaks related to specific emails i cant see password column or hash they are empty 
![recon-ng](https://user-images.githubusercontent.com/32272013/85386999-57511280-b555-11ea-838c-c98de9ec440e.PNG)

**Comment by MrJester** [comment]
The password or hash was included in the response from the server for those accounts.

**Comment by lanmaster53** [comment]
HIBP doesn't give away that data. Or at least it didn't when I wrote these modules. If they do now, then I'm all for someone upgrading them to use the latest API, etc.

**Comment by MrJester** [comment]
Correct data is not in the response. Closing
