### ISSUE TITLE
findsubdomains module broken

### ISSUE THREAD

**Issue by leebaird** [lanmaster53/recon-ng-marketplace#160]
**Module Name**
Which module is affected?
https://github.com/lanmaster53/recon-ng-marketplace/blob/master/modules/recon/domains-hosts/findsubdomains.py

**Bug Description**
recon/domains-hosts/findsubdomains module broken
v1.0

**Steps to Reproduce**
1. modules load recon/domains-hosts/findsubdomains
2. run

**Expected Behavior**
Results

**Additional Context**

```
----------------------
<various domains>
----------------------
[!] Error retrieving results.
```

**Comment by lanmaster53** [comment]
Please enable debugging or something. There's not enough information here. Thanks.

**Comment by MrJester** [comment]
This is a duplicate and known issue. Follow Issue #73
