### ISSUE TITLE
whoxy_dns module broken

### ISSUE THREAD

**Issue by leebaird** [lanmaster53/recon-ng-marketplace#161]
**Module Name**
Which module is affected?
https://github.com/lanmaster53/recon-ng-marketplace/blob/master/modules/recon/companies-domains/whoxy_dns.py

**Bug Description**
whoxy_dns module broken
v1.0

**Steps to Reproduce**
1. modules load recon/companies-domains/whoxy_dns
2. run

**Expected Behavior**
Results.

**Additional Context**

```
[!] 'NoneType' object is not iterable.
```

**Comment by lanmaster53** [comment]
Please enable debugging or something. There's not enough information here. Please see https://github.com/lanmaster53/recon-ng/wiki/Troubleshooting#troubleshooting. Thanks.

**Comment by MrJester** [comment]
Just tested this again and appears to be working for the half dozen test cases I just tried so would like to know what values you were using to cause this error.
