### ISSUE TITLE
module findsubdomains requires an update due to new website and API requirement.

### ISSUE THREAD

**Issue by preeset** [lanmaster53/recon-ng-marketplace#169]
**Module Name**
recon-ng/modules/domains-hosts/findsubdomains
https://github.com/lanmaster53/recon-ng-marketplace/tree/master/modules/recon/domains-hosts

**Bug Description**
"[ ! ] Error retrieving results."
The developer changed the tool to a new website and an API key is now required.

**Steps to Reproduce**
1. modules load recon/domains-hosts/findsubdomains
2. run

**Expected Behavior**
info: "Queries the FindSubDomain page for sub-domain information in a domain."

**Additional Context**
API Documents:
https://spyse.com/api#/domain/subdomainSpeaking with someone from the company I was given an example command to pull the requested data:

Example code to execute the GET using their new site & API:
curl -X GET "https://api.spyse.com/v3/data/domain/subdomain?domain=Your_target" -H "accept: application/json"

**Comment by MrJester** [comment]
This is a duplicate issue of #73 which is already fixed with PR #165
