### ISSUE TITLE
recon/contacts-credentials/scylla

### ISSUE THREAD

**Issue by kellylom** [lanmaster53/recon-ng-marketplace#170]
**Module Name**
recon/contacts/credentials/scylla
https://github.com/lanmaster53/recon-ng-marketplace/tree/master/modules/recon/contacts/credentials/scylla

**Bug Description**
the error i receive is invalid response 

**Steps to Reproduce**
\[Steps to reproduce the behavior:
1. Load module
2. type info to make sure source is set to default
3. run
4. errors out [!] Invalid response.

**Expected Behavior**
expected behavior is to query and capture credentials.

**Additional Context**
I submitted this issue on the Recon-ng repository about 13 days ago.

**Comment by MrJester** [comment]
Can you please provide more details possibly a screenshot of what you were searching for.

**Comment by kellylom** [comment]
![bug](https://user-images.githubusercontent.com/35275620/93120472-6695b700-f691-11ea-96a1-5b7f3023dbc5.PNG)

**Comment by kellylom** [comment]
It harvests contacts from the db and i have 6 or so contacts in the email column that should fulfill the requirement

**Comment by lanmaster53** [comment]
@MrJester Even though this is now closed, does the same issue apply to the domain scylla module?
