### ISSUE TITLE
[!] Error getting results.

### ISSUE THREAD

**Issue by 7savan** [lanmaster53/recon-ng-marketplace#172]
Hi, 

I'm facing the Error that I'm not able to get the result. Please help me to resolve it.
![Screenshot from 2020-07-21 18-46-35](https://user-images.githubusercontent.com/63670818/88059606-b91b9100-cb82-11ea-8d66-7df04dd40486.png)

**Comment by lanmaster53** [comment]
Unable to replicate.

```
[recon-ng][default][hackertarget] > options set SOURCE example.com
SOURCE => example.com
[recon-ng][default][hackertarget] > run

-----------
EXAMPLE.COM
-----------
[*] Country: None
[*] Host: example.com
[*] Ip_Address: 93.184.216.34
[*] Latitude: None
[*] Longitude: None
[*] Notes: None
[*] Region: None
[*] --------------------------------------------------
[*] Country: None
[*] Host: www.example.com
[*] Ip_Address: 93.184.216.34
[*] Latitude: None
[*] Longitude: None
[*] Notes: None
[*] Region: None
[*] --------------------------------------------------

-------
SUMMARY
-------
[*] 2 total (2 new) hosts found.
```

**Comment by MrJester** [comment]
Can you attach a screen shot after setting verbosity to 2. 

From the main menu 

options set verbosity 2 

or from within a module

goptions set verbosity 2

**Comment by lanmaster53** [comment]
While not an exact duplicate, same result. Everything is working as expected, so it. must be an environmental issue of some sort. Going to close.

**Comment by moranski7** [comment]
I got this same issue. After looking into it, the problem is that the hackertarget API is returning "API count exceeded - Increase Quota with Membership".
