### ISSUE TITLE
Error String indices must be integers with hibp_paste

### ISSUE THREAD

**Issue by ngolarva** [lanmaster53/recon-ng-marketplace#191]
**To save some time, have you:**
- [ ] Checked the [wiki](https://github.com/lanmaster53/recon-ng/wiki) 
- [ ] Checked previously answered [questions](https://github.com/lanmaster53/recon-ng-marketplace/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+label%3Aquestion)

**Please ask the question below**  
\[Please be as detailed as possible.\]

**Comment by EstimatedProphet** [comment]
I fixed this by changing
`headers = {'hibp-api-key': self.keys['hibp_api']}`
to
`headers = {'hibp-api-key': self.keys.get('hibp_api')}`

**Comment by Cy-Beard** [comment]
> I fixed this by changing
> `headers = {'hibp-api-key': self.keys['hibp_api']}`
> to
> `headers = {'hibp-api-key': self.keys.get('hibp_api')}`
> 
> You'll need to exit recon-ng and restart it for it to pick up the change in hibp_paste.py

I am having this same issue. For the solution you proposed, how or where do I enter that command? I have tried from the recon-ng but I get it's not a valid command.

**Comment by v01dlight** [comment]
He said "in hibp_paste.py" so I assume he means in the python file which contains the code for the module. Should be located here:
`/home/<YOUR USER NAME>/.recon-ng/modules/recon/contacts-credentials/hibp_paste.py`

**Comment by lanmaster53** [comment]
The only difference between mine and @Cy-Beard lines of code is that one will throw an exception when there is no API key set, and the other will return `None`. Therefore, the recommendation doesn't fix the issue. It merely hides it. The exception is an indicator that something is wrong. There was also an indicator of the need to add an API key when you installed the module. See #212 for an example. Therefore, the proper fix it to get and add a HIBP API key to the framework. It won't work without it, even if you don't get an error.
