### ISSUE TITLE
get ipinfodb api keys

### ISSUE THREAD

**Issue by akego** [lanmaster53/recon-ng-marketplace#192]
**To save some time, have you:**
- [ ] Checked the [wiki](https://github.com/lanmaster53/recon-ng/wiki) 
- [ ] Checked previously answered [questions](https://github.com/lanmaster53/recon-ng-marketplace/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+label%3Aquestion)

**Please ask the question below**  
\[Please be as detailed as possible.\]

**Comment by MrJester** [comment]
Are you asking how to get an API key? https://ipinfodb.com/api
