### ISSUE TITLE
HTMLParser error using module xssed

### ISSUE THREAD

**Issue by stevenbauermn** [lanmaster53/recon-ng-marketplace#205]
**Module Name**
Which module is affected?
https://github.com/lanmaster53/recon-ng-marketplace/tree/master/modules/xssed

**Bug Description**
\[A Python HTMLParser error occurs when using the xssed module. Most likely due to a Python deprecation of the HTMLParser.\]
```
[!] 'HTMLParser' object has no attribute 'unescape'.
[!] Something broken? See https://github.com/lanmaster53/recon-ng/wiki/Troubleshooting#issue-reporting.
```
**Steps to Reproduce**
\[Steps to reproduce the behavior:
1. 'module install recon/domains-vulnerabilities/xssed'
2. 'module load recon/domains-vulnerabilities/xssed'
3. 'options set SOURCE <website>'
4. 'run'
5. Results:
```
-----------------
<website>
-----------------
[!] 'HTMLParser' object has no attribute 'unescape'.
[!] Something broken? See https://github.com/lanmaster53/recon-ng/wiki/Troubleshooting#issue-reporting.
```

**Expected Behavior**
\[Up to the first 20 XSS records, if any exists, associated with the SOURCE.\]

**Comment by lanmaster53** [comment]
This was a core issue that should have been fixed with https://github.com/lanmaster53/recon-ng/commit/050ca135252d3d6fcb09b1046dc99af28b46d8b7.
