### ISSUE TITLE
I just started with Recon-ng and I keep getting an error message when I run any of the scylla

### ISSUE THREAD

**Issue by jrmsq** [lanmaster53/recon-ng-marketplace#206]
**To save some time, have you:**
- [ ] Checked the [wiki](https://github.com/lanmaster53/recon-ng/wiki) 
- [ ] Checked previously answered [questions](https://github.com/lanmaster53/recon-ng-marketplace/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+label%3Aquestion)

**Please ask the question below**  
\[Please be as detailed as possible.\]

Each time I tried to run scylla I get the following messages. Any help ?

[!] HTTPSConnectionPool(host='scylla.sh', port=443): Max retries exceeded with url: /search?q=Email%3A%22%40ocalaeye.com%22&size=100&start=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f31e5268ca0>: Failed to establish a new connection: [Errno -2] Name or service not known')).                                                                                                                                                                 
[!] Something broken? See https://github.com/lanmaster53/recon-ng/wiki/Troubleshooting#issue-reporting.

**Comment by MrJester** [comment]
Appologize but the owner of the Scylla website has taken down the website and it is no longer accessible.

**Comment by jrmsq** [comment]
Thank you, Ryan, any alternative tool that does similar things?

Regards,

JOHNY R. METELLUS, MBA, PMP

MSCA Office 365 Certified

(305) 766-4396
***@***.***

<https://www.linkedin.com/in/johnymetellus>

**Comment by MrJester** [comment]
Not that gets you the same data. The breach data that was in Scylla is floating around on the web if you wanted to just download it and search it yourself though.
