### ISSUE TITLE
Profiler error

### ISSUE THREAD

**Issue by sjd0** [lanmaster53/recon-ng-marketplace#238]
**Profiler**
Which module is affected?
https://github.com/lanmaster53/recon-ng-marketplace/tree/master/modules/recon/profile-profiles/profiler

**Bug Description**

[!] Extra data: line 1 column 4 (char 3).
[!] Something broken? See https://github.com/lanmaster53/recon-ng/wiki/Troubleshooting#issue-reporting.   

**Steps to Reproduce**
\[Steps to reproduce the behavior:
1. typed same command again:  run

**Expected Behavior**
\[A clear and concise description of the expected behavior.\]

**Screenshots**
[recon-ng][default][profiler] > show profiles

  +---------------------------------------------------------------------------------+
  | rowid |       username       | resource | url | category | notes |    module    |
  +---------------------------------------------------------------------------------+
  | 1     | deoshiatsu@gmail.com |          |     |          |       | user_defined |
  +---------------------------------------------------------------------------------+

[*] 1 rows returned
[recon-ng][default][profiler] > run
[*] Retrieving https://raw.githubusercontent.com/WebBreacher/WhatsMyName/master/web_accounts_list.json...

  Looking Up Data For: Deoshiatsu@Gmail.Com
  -----------------------------------------
[!] Extra data: line 1 column 4 (char 3).
[!] Something broken? See https://github.com/lanmaster53/recon-ng/wiki/Troubleshooting#issue-reporting.   

**Additional Context**
following newbie book on ethical hacking running recon-ng as per book instructions

**Comment by cbrunnkvist** [comment]
Duplicates #233

**Comment by sjd0** [comment]
So https://github.com/cbrunnkvist how do I fix the problem. Can't make sense out of #233

**Comment by lanmaster53** [comment]
Duplicate #233
