### ISSUE TITLE
BUG REPORT

### ISSUE THREAD

**Issue by martossa111** [lanmaster53/recon-ng-marketplace#247]
**Module Name**
Which module is affected?
https://github.com/lanmaster53/recon-ng-marketplace/tree/master/modules/[FILL ME IN]

**Bug Description**
\[A clear and concise description of the bug.\]

**Steps to Reproduce**
\[Steps to reproduce the behavior:
1. Go to NODE.JS
4. See error\]

**Expected Behavior**
\[A clear and concise description of the expected behavior.\]

**Screenshots**
\[If applicable, screenshots to help explain the problem.\]

**Additional Context**
\[Any other context about the problem.\]

**Comment by lanmaster53** [comment]
This literally makes no sense. Node.js? Not enough context. File a new issue with adequate information if the problem persists. Thanks.
