### ISSUE TITLE
recon/hosts-hosts/ssltools - Possible removal

### ISSUE THREAD

**Issue by MrJester** [lanmaster53/recon-ng-marketplace#33]
This module is a duplicate of ssl_san which is querying the SSLTools API to collect this same information.

**Comment by cam-barts** [comment]
The ssltools module does everything that ssl_san does and some extra. For that reason, I think it should be the ssl_san mod that gets removed.

**Comment by MrJester** [comment]
These modules are actually not duplicates so we won’t be removing either one.

**Comment by cam-barts** [comment]
@MrJester Great! We can probably close this then right?
