### ISSUE TITLE
recon/domains-contacts/pgp_search - Not working

### ISSUE THREAD

**Issue by lanmaster53** [lanmaster53/recon-ng-marketplace#38]
The resource is offline. I reached out to them. They acknowledged a known issue and recommended we move to http://pool.sks-keyservers.net:11371/. Should be an easy switch.

**Comment by cam-barts** [comment]
I'm not seeing pgp_search anywhere

**Comment by lanmaster53** [comment]
I must have removed it prior to the migration. See the attached file (renamed to txt to get around Github's file extension filter).

[pgp_search.txt](https://github.com/lanmaster53/recon-ng-marketplace/files/3425017/pgp_search.txt)

**Comment by azRKI3H72go4QUPe** [comment]
Was able to get the new updated code above (pgp_search.txt) and turn it into a .py file.

But when running the module it says, "Request() missing 1 required positional argument - 'url'."

Any ideas what is going wrong or how to fix?

**Comment by cam-barts** [comment]
I have it on my to do list to take care of it this weekend if someone else hasn't already, but if you need it today, I think I could probably fiddle around with it

**Comment by lanmaster53** [comment]
@cam-barts I'm pretty sure this is broken again. In fact, it looks like the interface has changed. Also, i get a 504 gateway error every time I search. Is there a better key server we could use?

**Comment by cam-barts** [comment]
@lanmaster53 Honestly I don't know much about pgp, I just picked up the issue to try and help out. I can certainly look into it, but I'm not sure I will find anything any faster than you might of.

**Comment by cam-barts** [comment]
http://pgp.key-server.io/ looks up and running.

**Comment by lanmaster53** [comment]
It looks up, but searches fail. Same as before. The new key server is working, but the dev pushed out a new interface. I updated the module locally last night and will resolve this issue shortly. Thanks Cam!

**Comment by cam-barts** [comment]
Search doesn't look like it's failing to me. I guess it's the terms. I found paulfurley.com had a key from an article he wrote, and this is the search feedback http://pgp.key-server.io/pks/lookup?search=paulfurley.com&fingerprint=on&op=vindex

**Comment by lanmaster53** [comment]
That's not a bad option either. Went with the recommended server for now, but this is good to know.
