### ISSUE TITLE
Dependency required

### ISSUE THREAD

**Issue by e2002e** [lanmaster53/recon-ng-marketplace#41]
I don't know how to deal with this issue, can you please tell me ?
[!] Module 'recon/domains-hosts/brute_hosts' disabled. Dependency required: ''dns''.
recon-ng complains about dns dependency.

**Comment by lanmaster53** [comment]
Please read the documentation on the Wiki. Following the Getting Started guidance will solve this issue.

https://github.com/lanmaster53/recon-ng/wiki
