### ISSUE TITLE
recon/contacts-profiles/fullcontact.py

### ISSUE THREAD

**Issue by lanmaster53** [lanmaster53/recon-ng-marketplace#44]
If the API responds with a contact that doesn't have any email addresses, it fails out at line 65. The reason it works sometimes is because of line 49, but even then it isn't working properly because it only stores the last email address received (the last iteration of the for loop). There needs to be better logic that detects if there are several emails, then creates a contact for each one, but will also create a single contact if there are none. Also, any other fields that can return multiple results also need to be considered here.

**Comment by cam-barts** [comment]
I can take this. I have some questions though. Considering this pulls emails from contacts anyway, if the emails['value'] is empty, why not set it to the input email to begin with? Something to the effect of
```python
# Start with input email anyway
emails = [entity]
for email in resp.json()['details'].get('emails'):
    emails.append(email)

# For each email, create a new contact
for email in emails:
   self.insert_contacts(first_name=first_name, middle_name=middle_name, last_name=last_name, title=title, email=email, region=region)
```

That would solve erring out and multiple emails.

**Comment by lanmaster53** [comment]
Yeah, that works. I guess i had forgotten that the email address was the original input to begin with. Are there any other categories (i.e. region) that we need to also account for multiple responses?
