### ISSUE TITLE
Modules are completely gone *EDIT: FIXED and I'm a Big Dummy*

### ISSUE THREAD

**Issue by safesecs** [lanmaster53/recon-ng-marketplace#55]
For some reason, my entire modules package/directory... is gone.  Where can I go and get these?  Yes, newbie shit here... don't troll. Or do, its kind of a dumb question.

**Comment by cam-barts** [comment]
You can clone https://github.com/lanmaster53/recon-ng-marketplace.git into your .recon directory.

**Comment by yodatron** [comment]
cam-barts, you gaveme this  same suggestion in the main recon-ng issues section. After cloning it to the dir recon-ng loads and says 'no mods loaded'. What could be the problem?

**Comment by cam-barts** [comment]
@yodatron @safesecs Sorry gents, I was giving bad info. I think the proper way to do it now is with `marketplace install all`. That should do all of the work for you.

**Comment by yodatron** [comment]
cool...run it in terminal or the recon-ng console?

**Comment by yodatron** [comment]
nvmd...I got it....:)

**Comment by safesecs** [comment]
Thanks!

**Comment by safesecs** [comment]
Welp, this isn't doing too well.  this is what I get .  I checked my firewall, nothing being blocked.

[recon-ng][default] > marketplace install all
[!] Supporting file download for discovery/info_disclosure/cache_snoop failed: (av_domains.lst).
[!] Module installation aborted.
[!] HTTPSConnectionPool(host='raw.githubusercontent.com', port=443)  Max retries exceeded with url  /lanmaster53/recon-ng-modules/master/data/av_domains.lst (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f394e09fcd0>  Failed to establish a new connection  [Errno -2] Name or service not known')).

Any ideas?  I am running Kali in a VM... but all tcp connections are allowed

**Comment by safesecs** [comment]
I have also checked marketplace info all.... there isn't a damn thing installed.  I have no idea why this is, even after i purge the application and reinstalled... soooooo this is getting nice and tricky.  I created a policy in my firewall to temporarily allow this with no restrictions, just in case.  Nope, not the firewall placking.

**Comment by MrJester** [comment]
So there are no modules installed because they have all moved to the marketplace. So you have to manually install them.  Just like it was stated above you need to run

marketplace install all 

and that will install ALL the modules or you can look within the marketplace with

marketplace search 

Then pick and choose which modules you would like installed. Not sure what error you are running into above with the HTTPs erro but I would guess you are having issues conencting to the github repo so you may want to check your firewall logs. I just ran 

marketplace install all on my Kali instance and had no issues installing everything.

**Comment by safesecs** [comment]
well holy hell... I have no clue... but it wasn't my firewall... for some reason up/downing my int did the trick.  Now I have another issue to troubleshoot... but bouncing my connection in Kali did the trick.  So strange.  OK, thanks.  I just renamed myself to "@bigdummy"

**Comment by safesecs** [comment]
Fixed... "Hey, how about checking your interface..." says me.

**Comment by safesecs** [comment]
Well, this is the biggest pain... "show modules" doesn't show anything... like it is not even a command. "use" is not even an option.... so I cannot "use recon/domain-hots/****" at all... what has happened to my recon-ng?

**Comment by MrJester** [comment]
You obviously have not read the wiki. I would suggest looking back at that. There were some huge changes in v5 to the command syntax and structure.

**Comment by safesecs** [comment]
yeah, im seeing that now... man, thanks for being patient... I'm not going to dive deep into that.... exiting stage left now.
