### ISSUE TITLE
recon/hosts-hosts/ipinfodb - Timeout error

### ISSUE THREAD

**Issue by azRKI3H72go4QUPe** [lanmaster53/recon-ng-marketplace#56]
Even with a valid key from IPInfoDB, getting a timeout error when submitting IPs to the module for IP to geolocation identification. Anyone else having this same issue?

Even set the timeout to 240 seconds to allow extra time, still doesn't work.

**Comment by lanmaster53** [comment]
Interesting. Doesn't seem to be an issue here. Do you have any DNS filtering in place that could be blocking the domain lookup for ipinfodb?

**Comment by azRKI3H72go4QUPe** [comment]
Was able to figure this out. There is something wrong with the ipinfodb module SOURCE default. 

The ipinfodb module SOURCE default is usually this:
SELECT DISTINCT ip_address FROM hosts WHERE ip_address IS NOT NULL

If there are multiple (non-distinct) occurrences of the same IP address in the hosts table, then the module would fail and give an error. To avoid this, by changing the SOURCE from default to a custom query instead, it now works. Below is the way to change that once the ipinfo module is loaded; notice how it takes the word DISTINCT out from the query:
options set SOURCE query SELECT ip_address FROM hosts

It may not be pretty and it will also send multiple requests to IPInfoDB asking about the same IP address, but it works. It may be good to still keep in the WHERE ip_address IS NOT NULL at the end of the query, but that wasn't tested, sorry.

Maybe you can update the ipinfodb module to change the SOURCE default to the above change so it's not so picky in requesting IP geo-location from IPInfoDB?

**Comment by lanmaster53** [comment]
I'm not sure this makes any sense. The data coming from the database has nothing to do with a network timeout. In fact, your query should error out if it comes across a record without an IP address, because it will try to resolve the location for a NoneType object, which will fail.

**Comment by lanmaster53** [comment]
Unable to replicate the issue and have been using it with no problem.
