### ISSUE TITLE
import/list Error Messages missing

### ISSUE THREAD

**Issue by MrJester** [lanmaster53/recon-ng-marketplace#57]
Need to properly error when the correct options are not set. When I was missing the COLUMN option all that is returned for an error is 

[recon-ng][health.mil][list] > options set TABLE domains
TABLE => domains
[recon-ng][health.mil][list] > run
[!] Something broken? See https://github.com/lanmaster53/recon-ng/wiki/Troubleshooting#issue-reporting.

Would be easier if we just had a message to tell the user they are missing a required option.

**Comment by lanmaster53** [comment]
Agreed, and it should be doing that. What verbosity level are you running at?

**Comment by MrJester** [comment]
This was with the default verbosity so I think 0 or 1

**Comment by lanmaster53** [comment]
Ok, default is 1 (verbose) and should be showing something. 0 may not. Ill have to check.

**Comment by lanmaster53** [comment]
I can't even replicate this, lol. I have no idea what error you caused, but I don't think it was caused because of an options setting.
