### ISSUE TITLE
problem with cache_snoop modules

### ISSUE THREAD

**Issue by aentezari** [lanmaster53/recon-ng-marketplace#63]
**cache_snoop**

https://github.com/lanmaster53/recon-ng-marketplace/blob/master/modules/discovery/info_disclosure/cache_snoop.py

**Bug Description**
\[AttributeError: module 'dns' has no attribute 'query'\]

**Comment by lanmaster53** [comment]
Please update the issue with everything requested in the issue template. There isn't enough information here to replicate or troubleshoot your specific issue. Thanks!

**Comment by aentezari** [comment]
after install or test recon-ng on some Linux Distro such Kali or parrot I get Same this error

**Comment by lanmaster53** [comment]
See below. I can't replicate. No issues here. Distros are notorious for using old versions of tools that get updated as often as Recon-ng. I suggest doing a fresh install based on the guidance in the wiki, then checking back with us if problems persist.

```
[recon-ng][default][cache_snoop] > run
[*] dnl-01.geo.kaspersky.com => Snooped!
[*] download797.avast.com => Not Found.
[*] downloads2.kaspersky-labs.com => Not Found.
[*] es-latest-3.sophos.com/update => Not Found.
[*] es-web-2.sophos.com => Not Found.
[*] es-web-2.sophos.com.edgesuite.net => Not Found.
```

**Comment by l4jos** [comment]
I'm getting error

 Module 'dns' has no attribute 'message'.

Recon-NG Version 5.1

**Comment by cam-barts** [comment]
@l4jos Can you give any more context? I just tested python 3.6 and 3.7, running recon-ng 5.1, with dnspython 1.16.0, and could not reproduce your error.

**Comment by l4jos** [comment]
Me neither anymore. Probably on my side...

[recon-ng][default][cache_snoop] > run
[*] dnl-01.geo.kaspersky.com => Not Found.
[*] download797.avast.com => Not Found.
[*] downloads2.kaspersky-labs.com => Not Found.
[*] es-latest-3.sophos.com/update => Not Found.
[*] es-web-2.sophos.com => Not Found.
[*] es-web-2.sophos.com.edgesuite.net => Not Found.
[*] es-web.sophos.com => Not Found.
[*] es-web.sophos.com.edgesuite.net => Not Found.
[*] forefrontdl.microsoft.com => Not Found.
[*] guru.avg.com => Not Found.
[*] liveupdate.symantec.com => Snooped!

**Comment by lanmaster53** [comment]
In that case...

**Comment by l4jos** [comment]
Hey, the cache snoop was wrong. I went to a mate and I asked him 'do you have a symantec product?'
'No, I don't have Norton resource-hungry products'

**Comment by lanmaster53** [comment]
There are a lot of variables at play. Were you querying their internal DNS directly? Was there a BYOD device that perhaps made a call to that DNS for Symantec? Bottom line, all the module does is make a DNS query. That's it. There's nothing to really be broke about it. If anything in that network resolved the symantec update host, which is probably pretty likely even in environments where it isn't officially deployed, then it will cache.
