### ISSUE TITLE
recon/domains-companies/pen description inaccurate

### ISSUE THREAD

**Issue by lanmaster53** [lanmaster53/recon-ng-marketplace#72]
**Module Name**

https://github.com/lanmaster53/recon-ng-marketplace/tree/master/modules/recon/domains-companies/pen.py

**Bug Description**

The description talks about updating the domains table, but it updates the companies table. I think this is a copy and paste issue from a similar module with similar logic that harvests domain.

**Steps to Reproduce**

1. Install the module.
2. Load the module.
3. Read the module info.

**Expected Behavior**

Have an accurate description of its behavior.

**Comment by lanmaster53** [comment]
recon/domains-contacts/pen suffers from the same issue. Should probably check all pen modules.

**Comment by lanmaster53** [comment]
In fact, check all pen modules. They seem to all be affected in some way.

**Comment by cam-barts** [comment]
This issue seems like a perfect candidate for the Hacktoberfest and Good First Issue labels. Otherwise I can pick it up.

**Comment by lanmaster53** [comment]
I have no idea what that means, lol. I already started fixing them locally last night and will push out some fixes here in a bit. What are Hacktoberfest and Good First?

**Comment by cam-barts** [comment]
https://hacktoberfest.digitalocean.com/details Its a program run by Digital Ocean every October to promote contributing to open source. They send you a free t shirt if you make 4 pull requests in October if you've signed up. "Good First Issue" is a common label that many bootcamps and online coding resources tell you to search by if you are just starting out coding and want to contribute to open source.
