### ISSUE TITLE
Recon-ng wont load freegeoip 

### ISSUE THREAD

**Issue by LupinTr3s** [lanmaster53/recon-ng-marketplace#82]
When I'm running recon and I go to load the freegeoip into resolve it says invalid module. I'm trying to do this for a class but not getting alot of feed back from the professor. 

I am able to get the ip address but whe  I go to get the latitude and longitudes via freegeoip nothing happens. Is there another geo module I can load or is there a way to add the freegeoip module that I'm missing. Thank you in advance

**Comment by lanmaster53** [comment]
It's a pretty bold move to use something like this as part of a long term lesson plan. The resources that these modules use are constantly changing, which causes the modules come and go as the community maintains them. I would advise your teacher/professor to be more general about the assignment and emphasize the data over the module used to harvest it.

To find modules that geolocate an IP, search the marketplace using the `marketplace search -locations` command. However, I don't think there are functional at the moment. There's nothing you can do about that except write a functional module, fix a broken one, or wait until someone else does. Please send your professor this link for his/her situational awareness.

**Comment by Sagarrawat304** [comment]
when we use any modules about location the it will display eror some moudles are not working efficently ipsatck also give an eror
