### ISSUE TITLE
import/list: Not all arguments converted during string formatting.

### ISSUE THREAD

**Issue by fmtbkgiddiqq** [lanmaster53/recon-ng-marketplace#84]
**Module Name**
Which module is affected?
https://github.com/lanmaster53/recon-ng-marketplace/tree/master/modules/import/list

**Bug Description**
When importing a list of multiple items (one per line), the module only imports the first item and then throws an error. "[!] Not all arguments converted during string formatting."

**Steps to Reproduce**
modules load import/list
options set TABLE domains
options set COLUMN domain
options set FILENAME /home/blah/domains.txt
run

At first I assumed my input files were bad or poorly formatted, however I was able to reproduce the issue by opening an editor and manually typing in a few lines. 

**Expected Behavior**
Previously (before 5 -> 5.1 upgrade?) the module would execute without error, processing all list items in the text file. Items already in the database would not be duplicated. Items present in the file, which were not currently in the database, would be inserted into the database table.

**Screenshots**
\[If applicable, screenshots to help explain the problem.\]

**Additional Context**
recon-ng version 5.1.0
python 3.7.3

**Comment by cam-barts** [comment]
Hi @fmtbkgiddiqq. From looking at it, I was unable to reproduce on my machine. I created a test file with cnn.com, bs.com, and adatum.com in it, and loaded it just fine. It shouldn't matter, but I loaded the txt file like so 
```bash
echo "cnn.com" > test.txt
echo "bs.com" >> test.txt
echo "adatum.com" >> test.txt
```
As you can see from the screenshot below, they loaded properly. 

![list](https://user-images.githubusercontent.com/13058567/70335634-a9c71d80-1815-11ea-9101-4a367c310d1b.png)

Is there any other context you are able to give about the file you are attempting to load?

**Comment by fmtbkgiddiqq** [comment]
Thank you for your swift reply. I will assume its a problem with my system for not and will report back when I find something actionable.

**Comment by cam-barts** [comment]
@fmtbkgiddiqq Ah, I see. I am receiving the same error, and the root cause is when we added a "notes" column to each table. I can shoot up a PR with some better handling. It is remedied in the meantime be removing that part in the data dictionary, in the framework.py file, in the recon-ng core directory.
