### ISSUE TITLE
Issue running the discovery/info_disclosure/interesting_files module

### ISSUE THREAD

**Issue by LucSai** [lanmaster53/recon-ng-marketplace#85]
**Module Name**
Which module is affected?
Module name: discovery/info_disclosure/interesting_files
https://github.com/lanmaster53/recon-ng-marketplace/tree/master/modules/discovery/info_disclosure/interesting_files

**Bug Description**
When running the  interesting_files modules using the hosts from the database (I used the module recon/domains-hosts/bing_domain_web to find some hosts), the module only runs for a few seconds and then throws an error. "[!] Can't concat str to bytes.
[!] Something broken? See https://github.com/lanmaster53/recon-ng/wiki/Troubleshooting#issue-reporting."

**Steps to Reproduce**
1. add some hosts to the database (I used the module recon/domains-hosts/bing_domain_web to find some hosts and add them)
2. marketplace refresh
3. marketplace install discovery/info_disclosure/interesting_files
4. modules load discovery/info_disclosure/interesting_files
5. run
6. it runs for a few seconds and then it trow the error (check screenshot 2 and outputDebugs.txt)

**Expected Behavior**
it should provide a list of interesting files on the hosts and download them

**Screenshots**
Screenshot showing the options used in the module:
![Screenshot 2019-12-09 at 10 43 19](https://user-images.githubusercontent.com/44528713/70434388-fc097800-1a7b-11ea-88f7-531948d67e83.png)

Screenshot showing the error used in the module:
![Screenshot 2019-12-09 at 10 44 10](https://user-images.githubusercontent.com/44528713/70434343-ded4a980-1a7b-11ea-9029-39b5fdd9413e.png)

Output text (setting the VERBOSTY lever to 2):
[outputDebugs.txt](https://github.com/lanmaster53/recon-ng-marketplace/files/3939548/outputDebugs.txt)

**Additional Context**
Platform: Macbook Air (Early 2015) macOS Catalina Version 10.15.1
Python version: 3.7.0
Recon-ng: recon-ng v5.0.1

**Comment by lanmaster53** [comment]
This is most certainly a error caused by converting to Python 3. In Python 3 all strings default to unicode type. In Python 2 they default to bytes type. We need to properly decode/encode here. This is a valid issue.
