### ISSUE TITLE
Issue in ipstack

### ISSUE THREAD

**Issue by OutdoorBoy** [lanmaster53/recon-ng-marketplace#86]
**Module Name**
Which module is affected?
https://github.com/lanmaster53/recon-ng-marketplace/tree/master/modules/ipstack

**Bug Description**
Have API key for ipstack and ipstack will not run. Is seems theh the API key is not used when executed. (See REQUEST section)

[recon-ng][cgi][ipstack] > keys add ipstack_api f64a7e2bad5d37e0407xxxxxxxxxxxxxx
[*] DATABASE => /home/jan/.recon-ng/keys.db
[*] QUERY => UPDATE keys SET value=? WHERE name=?
[*] VALUES => ('f64a7e2bad5d37e0407xxxxxxxxxxxxxx', 'ipstack_api')
[*] Key 'ipstack_api' added.
[recon-ng][cgi][ipstack] > run
[*] DATABASE => /home/jan/.recon-ng/workspaces/cgi/data.db
[*] QUERY => SELECT DISTINCT ip_address FROM hosts WHERE ip_address IS NOT NULL
[*] ========================= REQUEST =========================
url:    http://api.ipstack.com/64.254.16.84?access_key=None
method: GET /64.254.16.84?access_key=None
header: User-Agent: Recon-ng/v5
header: Accept-Encoding: gzip, deflate
header: Accept: */*
header: Connection: keep-alive
[*] ========================= RESPONSE =========================
status: 200 OK
header: Server: nginx
header: Date: Sat, 21 Dec 2019 15:22:15 GMT
header: Content-Type: application/json; Charset=UTF-8
header: Transfer-Encoding: chunked
header: X-Apilayer-Transaction-Id: 5933e2e4-6fd7-4fd1-a552-9e48dc4d514e
header: Access-Control-Allow-Methods: GET, HEAD, POST, PUT, PATCH, DELETE, OPTIONS
header: Access-Control-Allow-Origin: *
header: X-Request-Time: 0.008
body:   b'{"success":false,"error":{"code":101,"type":"invalid_access_key","info":"You have not supplied a valid API Access Key. [Technical Support: support@apilayer.com]"}}'
------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/share/recon-ng/recon/core/module.py", line 291, in do_run
    self.module_run(*params)
  File "/home/jan/.recon-ng/modules/recon/hosts-hosts/ipstack.py", line 25, in module_run
    region = ', '.join([jsonobj[x] for x in ['city', 'region_name'] if jsonobj[x]]) or None
  File "/home/jan/.recon-ng/modules/recon/hosts-hosts/ipstack.py", line 25, in <listcomp>
    region = ', '.join([jsonobj[x] for x in ['city', 'region_name'] if jsonobj[x]]) or None
KeyError: 'city'
------------------------------------------------------------
[!] Something broken? See https://github.com/lanmaster53/recon-ng/wiki/Troubleshooting#issue-reporting.
[*] DATABASE => /home/jan/.recon-ng/workspaces/cgi/data.db
[*] QUERY => INSERT OR REPLACE INTO dashboard (module, runs) VALUES ('recon/hosts-hosts/ipstack', COALESCE((SELECT runs FROM dashboard WHERE module='recon/hosts-hosts/ipstack')+1, 1))

**Steps to Reproduce**
\[Steps to reproduce the behavior:
1. Added API key for ipstack
2. hosts tabel is populated with data. Lots of ip_adresses
3. run ipstack and it crashes

**Expected Behavior**
Expected module to run and add locations in hosts table

**Screenshots**
\[If applicable, screenshots to help explain the problem.\]

**Additional Context**

[recon-ng][cgi] > options set VERBOSITY 1
VERBOSITY => 1
[recon-ng][cgi] > modules load recon/hosts-hosts/ipstack
[recon-ng][cgi][ipstack] > run
[!] 'city'.
[!] Something broken? See https://github.com/lanmaster53/recon-ng/wiki/Troubleshooting#issue-reporting.

**Comment by cam-barts** [comment]
Hey @OutdoorBoy, ran a test against 8.8.8.8 and the module looks like it's working (see screenshot). 
![Screenshot from 2019-12-27 13-44-02](https://user-images.githubusercontent.com/13058567/71528870-f8fdec80-28af-11ea-939b-be4773b0426d.png)
However, it looks like from the text that for some reason, you key isn't being loaded 

> =========================
url: http://api.ipstack.com/64.254.16.84?access_key=None

How are you adding your ipstack key? The command should be `keys add ipstack_api <your key>`. Note, if you put `ipstack` and not `ipstack_api`, it will not work with the module.

**Comment by cam-barts** [comment]
Also, running against the IP you provided (64.254.16.84) produces results as expected.

**Comment by cam-barts** [comment]
@OutdoorBoy If you run `keys list`, there aren't any duplicates or funny entries? The entry for ipstack_api actually has your key in it correct? Looking at the code in the framework, the function that returns the key returns `None` if the row doesn't exist in the table

**Comment by OutdoorBoy** [comment]
I removed the ipstack_api key from the keys table and inserted it again. Now it works. 
Thanks
Case closed
