### ISSUE TITLE
使用recon/contacts-credentials/hibp_paste报错

### ISSUE THREAD

**Issue by zx5200** [lanmaster53/recon-ng-marketplace#88]
你好,在使用recon/contacts-credentials/hibp_paste 出现报错。
![image](https://user-images.githubusercontent.com/34268894/71656747-9311d900-2d77-11ea-9a5b-0f71c5be324d.png)

我的 options set SOURCE xxxxxxx@qq.com如下结果
![image](https://user-images.githubusercontent.com/34268894/71656792-c48aa480-2d77-11ea-9c84-65fdcd854e47.png)

**Comment by cam-barts** [comment]
Hi @zx5200, 
The error you are receiving looks like it is due to now having an API key. When you run `keys list`, do you have a key listed for `hibp_api`?

**Comment by zx5200** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Cam"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月2日(星期四) 晚上8:40
收件人:&nbsp;"lanmaster53/recon-ng-marketplace"<recon-ng-marketplace@noreply.github.com&gt;;
抄送:&nbsp;"坚定"<376359318@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [lanmaster53/recon-ng-marketplace] 使用recon/contacts-credentials/hibp_paste报错 (#88)




Hi @zx5200,
 The error you are receiving looks like it is due to now having an API key. When you run keys list, do you have a key listed for hibp_api?

**Comment by griddd** [comment]
I have an API key, and I'm seeing the same error.  Similar error is happening in the hibp_breach module.  It appears as though the module is not passing the required "hibp-api-key" header in the HTTP request.  See attached debugging screenshot
![capture](https://user-images.githubusercontent.com/15107491/72171542-ccaa9b80-3398-11ea-9960-dcc4409dfdba.png)

**Comment by griddd** [comment]
Please ignore my last comment.  I'm running on Kali Linux, and updating fixed the problem.

Feel like such a goof :)

**Comment by lanmaster53** [comment]
Cool. Sounds like we can close this then. Thanks!
