### ISSUE TITLE
help in run module

### ISSUE THREAD

**Issue by rayan94444** [lanmaster53/recon-ng-marketplace#90]
plz help i already update my recon-ng and when i run any modules error raise (source contain no output)and can't run any modulo??

**Comment by cam-barts** [comment]
Hi @rayan94444. When you first load recon-ng, try this:
```
marketplace install all
```
Recon-ng since 5.0 implemented a marketplace model, where modules are not present by default. This command should get everything installed for you.

**Comment by lanmaster53** [comment]
This sounds like a general misunderstanding of the tool. Please see the wiki for guidance and let us know if you have any specific questions. Thanks. https://github.com/lanmaster53/recon-ng/wiki
