### ISSUE TITLE
certificate_transparency

### ISSUE THREAD

**Issue by matttheplanet** [lanmaster53/recon-ng-marketplace#94]
**Module Name**
Which module is affected?
https://github.com/lanmaster53/recon-ng-marketplace/tree/master/modules/certificate_transparency

**Bug Description**
I really like this module, but I noticed that the output is being stored in the hosts table in a format that isn't compatible with other modules. It is throwing multiple hostnames into a single host field in the hosts table. This breaks things like reverse_resolve because the host filed will then have data that isn't formatted like it is expected. 

So if the module runs through one cert that has multiple dns names/hosts in it, the module will save the data out to a single host field. Below is an example if this was run on one cert and 3 domains were found in it and then the data was saved to row1. This is what the host field would look like for the single row:
Domain1.com
Domain2.com
Domain3.com

Opposed to making a new row for each domain name/host discovered.

So after you run this module, (at least against the domains I just did) it breaks anything that uses the host field in the hosts database because a lot of the other modules can't handle the host field full of multiple domains and returns. If I have time I will see if I can adjust that. 

**Steps to Reproduce**
\[Steps to reproduce the behavior:
1. load the module
2. Run against a certificate that will return multiple dns/host names
3. Try to run recon/hosts-hosts/resolve

**Expected Behavior**
When discovering hosts, save each of them to a separate row in the table.

**Comment by MrJester** [comment]
Confirmed bug. Will be working on this one.

**Comment by MrJester** [comment]
This is actually fixed in a pull request awaiting merge with master. Closing for now.
