### ISSUE TITLE
ipstack module error

### ISSUE THREAD

**Issue by eliassal** [lanmaster53/recon-ng-marketplace#98]
I have a fresh new kalilinux 2020 setup and working correctly. I tried using ipstack module, when I run it I get

> [recon-ng][sierac][ipstack] > run
> [!] 'city'.
> [!] Something broken? See https://github.com/lanmaster53/recon-ng/wiki/Troubleshooting#issue-reporting.

Thanks for your help

**Comment by struggler142** [comment]
The link to this page reads "module issues"???  Is this not a module problem (same as his)????

**Comment by lanmaster53** [comment]
@struggler142 I think you misunderstand the above message. It was originally posted to the framework repository. See the note above that says "lanmaster53 transferred this issue from lanmaster53/recon-ng on Feb 13"?

I just tested the module and below is what came back:

```
[recon-ng][default] > modules load ipinfodb
[recon-ng][default][ipinfodb] > options set SOURCE 8.8.8.8
SOURCE => 8.8.8.8
[recon-ng][default][ipinfodb] > run
[*] 8.8.8.8 - 37.406,-122.079 - Mountain View, California, United States of America
[recon-ng][default][ipinfodb] >
```

I can't replicate the error. Please provide enough information to do so. Thanks!
