### ISSUE TITLE
ipinfodb not updating hosts table

### ISSUE THREAD

**Issue by eliassal** [lanmaster53/recon-ng-marketplace#99]
**Module Name**
Which module is affected?
https://github.com/lanmaster53/recon-ng-marketplace/tree/master/modules/ipinfodb

**Bug Description**
On a fresh new kali linux 2020, I run ipinfodb it returns back 1 result for the domain in the SOURCE option not for all domains in the hosts table also it works correcly when I hand a file with several domains but it never updates the hosts table with the locations

**Comment by lanmaster53** [comment]
That module description says, "'Leverages the ipinfodb.com API to geolocate a host by IP address. Updates the 'hosts' table with the results." It does transform domains. it transforms IP addresses into locations. As you can see in the description, it isn't designed to add new rows, just update the ones that are already there.

**Comment by MrJester** [comment]
When you set SOURCE it will only search for that value and not all values within the hosts table.
